/**
 * @file cvedix_image_record_control_meta.h
 * @brief Control meta for image recording trigger
 */

#pragma once

#include "cvedix_control_meta.h"

namespace cvedix_objects {
    /**
     * @brief Image recording command
     */
    class cvedix_image_record_control_meta: public cvedix_control_meta
    {

    private:
        /* data */
    public:
        cvedix_image_record_control_meta(int channel_index, 
                                    std::string image_file_name_without_ext,
                                    bool osd = false);
        ~cvedix_image_record_control_meta();

        // copy myself
        virtual std::shared_ptr<cvedix_meta> clone() override;

        // file name without extension, like 2022-10-20_22-30-20_aaa_bbb, which should be a meaningful and unique name.
        // generated by sender who want to record image
        std::string image_file_name_without_ext;

        // record type (osd frame or not)
        bool osd = false;
    };

}